---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/courses":
    delete:
      summary: Delete course by id.
      tags:
      - Courses
      parameters:
      - name: id
        in: query
        schema:
          type: query
          required:
          - id
      responses:
        '200':
          description: Course has been deleted.
    post:
      summary: Create course.
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: Course created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                description:
                  type: string
                estimated_time:
                  type: integer
                difficulty:
                  type: integer
                state:
                  type: string
    patch:
      summary: Update data of course.
      tags:
      - Courses
      parameters: []
      responses:
        '201':
          description: Course updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                description:
                  type: string
                estimated_time:
                  type: integer
                difficulty:
                  type: integer
                state:
                  type: string
    get:
      summary: Get course or list of courses.
      tags:
      - Courses
      parameters:
      - name: id
        in: query
        schema:
          type: query
          properties:
            id:
              type: integer
      responses:
        '200':
          description: ''
  "/reviews":
    delete:
      summary: Delete review by id.
      tags:
      - Reviews
      parameters:
      - name: id
        in: query
        schema:
          type: query
          required:
          - id
      responses:
        '200':
          description: Review has been deleted.
    post:
      summary: Create review.
      tags:
      - Reviews
      parameters: []
      responses:
        '201':
          description: Review created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                profile:
                  type: integer
                course_id:
                  type: integer
                text:
                  type: string
                mark_of_theory:
                  type: string
                mark_of_practice:
                  type: string
    patch:
      summary: Update data of review.
      tags:
      - Reviews
      parameters: []
      responses:
        '201':
          description: Review updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                profile:
                  type: integer
                course_id:
                  type: integer
                text:
                  type: string
                mark_of_theory:
                  type: string
                mark_of_practice:
                  type: string
    get:
      summary: Get review or list of reviews.
      tags:
      - Reviews
      parameters:
      - name: id
        in: query
        schema:
          type: query
          properties:
            id:
              type: integer
      responses:
        '200':
          description: ''
  "/skills":
    delete:
      summary: Delete skill by id.
      tags:
      - Skills
      parameters:
      - name: id
        in: query
        schema:
          type: query
          required:
          - id
      responses:
        '200':
          description: Skill has been deleted.
    post:
      summary: Create skill.
      tags:
      - Skills
      parameters: []
      responses:
        '201':
          description: Skill created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                skill_id:
                  type: integer
                course_id:
                  type: integer
    patch:
      summary: Update data of review.
      tags:
      - Skills
      parameters: []
      responses:
        '201':
          description: Skill updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                skill_id:
                  type: integer
                course_id:
                  type: integer
    get:
      summary: Get skill or list of skills.
      tags:
      - Skills
      parameters:
      - name: id
        in: query
        schema:
          type: query
          properties:
            id:
              type: integer
      responses:
        '200':
          description: ''
  "/students":
    delete:
      summary: Delete student by id.
      tags:
      - Students
      parameters:
      - name: id
        in: query
        schema:
          type: query
          required:
          - id
      responses:
        '200':
          description: Student has been deleted.
    post:
      summary: Create student.
      tags:
      - Students
      parameters: []
      responses:
        '201':
          description: Student created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                profile:
                  type: integer
                course_id:
                  type: integer
                pass_percentage:
                  type: numeric
                state:
                  type: string
    patch:
      summary: Update data of student.
      tags:
      - Students
      parameters: []
      responses:
        '201':
          description: Student updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                profile:
                  type: integer
                course_id:
                  type: integer
                pass_percentage:
                  type: numeric
                state:
                  type: string
    get:
      summary: Get student or list of students.
      tags:
      - Students
      parameters:
      - name: id
        in: query
        schema:
          type: query
          properties:
            id:
              type: integer
      responses:
        '200':
          description: ''
